#!/usr/bin/env python
"""
generate_task_bats.py — 从 data/tasks.json 统一生成 .bat + register_all_tasks.ps1

用法:
    python tools/generate_task_bats.py               # 生成全部文件
    python tools/generate_task_bats.py --dry-run      # 预览，不写盘
    python tools/generate_task_bats.py --backup       # 先备份现有文件再生成

单一真实来源: data/tasks.json → 所有 .bat + 注册脚本 + 文档

generated by generate_task_bats.py — DO NOT EDIT (手动修改将丢失，改 tasks.json)
"""
import json
import shutil
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

BASE_DIR = Path(__file__).resolve().parent.parent
TASKS_JSON = BASE_DIR / "data" / "tasks.json"
BACKUP_DIR = Path.home() / ".claude" / "backups" / datetime.now().strftime("%Y%m%d_%H%M")

# ── bat 模板 ────────────────────────────────────────────────────


def _bat_simple(meta: dict, task: dict) -> str:
    """静默执行: powershell -WindowStyle Hidden 包装，不弹窗"""
    cmd = _python_cmd(task)
    log = _abs_log(task['log_path'])
    cron_str = _cron_human(task.get("cron"), task)
    lines = [
        "@echo off",
        f"REM {task['description']} - {cron_str}",
        f"powershell -WindowStyle Hidden -Command \"cmd /c '{cmd} >> {log} 2>&1'\"",
        "",
    ]
    return "\n".join(lines)


def _bat_simple_exit(meta: dict, task: dict) -> str:
    """simple + exit /b %ERRORLEVEL%"""
    content = _bat_simple(meta, task)
    content += "exit /b %ERRORLEVEL%\n"
    return content


def _bat_powershell_hidden(meta: dict, task: dict) -> str:
    """powershell -WindowStyle Hidden 包一层，避免弹窗"""
    cmd = _python_cmd(task)
    log = _abs_log(task["log_path"])
    cron_str = _cron_human(task.get("cron"), task)
    # Use absolute paths for powershell
    py = meta["python_path"]
    script = f"{meta['work_dir']}\\{task['command']}"
    args_str = " ".join(task.get("args", []))
    parts = [
        "@echo off",
        f"REM {task['description']} - {cron_str}",
        f'powershell -WindowStyle Hidden -Command "cmd /c \'{py} {script} {args_str} >> {log} 2>&1\'"',
        "",
    ]
    return "\n".join(parts)


def _bat_closing_review(meta: dict, task: dict) -> str:
    """静默 + STATUS_CONTROL_C_EXIT 误报修复"""
    cmd = _python_cmd(task)
    log = _abs_log(task['log_path'])
    cron_str = _cron_human(task.get("cron"), task)
    lines = [
        "@echo off",
        f"REM {task['description']} - {cron_str}",
        "REM 注意: Python + akshare 退出时可能产生 STATUS_CONTROL_C_EXIT (3221225786)",
        "REM 此为误报(脚本已完成工作)，powershell 包装后以 exit 0 结束",
        f"powershell -WindowStyle Hidden -Command \"cmd /c '{cmd} >> {log} 2>&1'\"",
        "exit /b 0",
        "",
    ]
    return "\n".join(lines)


def _bat_lint(meta: dict, task: dict) -> str:
    """Lint 专用: PYTHONPATH + --local 分支支持，静默执行"""
    cron_str = _cron_human(task.get("cron"), task)
    py = meta['python_path']
    lines = [
        "@echo off",
        f"REM {task['description']} - {cron_str}",
        "REM 注册: SEL_MorningLint (08:30 每日)",
        "set PYTHONPATH=D:\\1989n\\stock_analysis",
        "",
        'if "%1"=="--local" (',
        f"    powershell -WindowStyle Hidden -Command \"cmd /c '{py} lint_wrapper.py'\"",
        ") else (",
        "    set FEISHU_SEND_ENABLED=true",
        f"    powershell -WindowStyle Hidden -Command \"cmd /c '{py} lint_wrapper.py'\"",
        ")",
        "",
        "exit /b %ERRORLEVEL%",
        "",
    ]
    return "\n".join(lines)


def _bat_multi_step(meta: dict, task: dict) -> str:
    """多步骤: 每步独立 powershell 静默调用 python + log"""
    cron_str = _cron_human(task.get("cron"), task)
    lines = [
        "@echo off",
        f"REM {task['description']} - {cron_str}",
    ]
    for step in task.get("steps", []):
        args_str = " ".join(step.get("args", []))
        cmd = f"{meta['python_path']} {step['command']} {args_str} >> {_abs_log(step['log_path'])} 2>&1"
        if step.get("timestamp"):
            log = _abs_log(step["log_path"])
            label = step["command"].replace(".py", "").replace("_", " ").title()
            cmd = f"echo [%DATE% %TIME%] {label} start >> {log} & {cmd} & echo [%DATE% %TIME%] {label} end >> {log}"
        lines.append(f"powershell -WindowStyle Hidden -Command \"cmd /c '{cmd}'\"")
    lines.append("")
    return "\n".join(lines)


def _bat_timestamp(meta: dict, task: dict) -> str:
    """记录起止时间戳，静默执行"""
    cmd = _python_cmd(task)
    log = _abs_log(task["log_path"])
    label = task["command"].replace(".py", "").replace("_", " ").title()
    cron_str = _cron_human(task.get("cron"), task)
    wrapped = f"echo [%DATE% %TIME%] {label} start >> {log} & {cmd} >> {log} 2>&1 & echo [%DATE% %TIME%] {label} end >> {log}"
    lines = [
        "@echo off",
        f"REM {task['description']} - {cron_str}",
        f"powershell -WindowStyle Hidden -Command \"cmd /c '{wrapped}'\"",
        "",
    ]
    return "\n".join(lines)


def _bat_pause(meta: dict, task: dict) -> str:
    """手动脚本: 静默执行，不弹窗不暂停"""
    cmd = _python_cmd(task)
    lines = [
        "@echo off",
        f"REM {task['description']} - 手动执行",
        f"powershell -WindowStyle Hidden -Command \"cmd /c '{cmd}'\"",
        "exit /b %ERRORLEVEL%",
        "",
    ]
    return "\n".join(lines)


# ── bat 选择器 ──────────────────────────────────────────────────

BAT_GENERATORS = {
    "simple": _bat_simple,
    "simple_exit": _bat_simple_exit,
    "powershell_hidden": _bat_powershell_hidden,
    "closing_review": _bat_closing_review,
    "lint": _bat_lint,
    "multi_step": _bat_multi_step,
    "timestamp": _bat_timestamp,
    "pause": _bat_pause,
}


# ── 工具函数 ────────────────────────────────────────────────────


def _python_cmd(task: dict) -> str:
    """生成 python 调用字符串"""
    args_str = " ".join(task.get("args", []))
    return f"{_META['python_path']} {task['command']} {args_str}".strip()


DATA_PREFIX = "D:\\1989n\\"


def _abs_log(path: str) -> str:
    """将相对 log_path 转为绝对路径。
    tasks.json 中 log_path 用相对路径 (如 stock_data/foo.log)，
    但 .bat 需要绝对路径，因为 cd 到 work_dir 后 stock_data 会解析为 work_dir/stock_data/。
    """
    if not path:
        return "nul"
    if path.startswith("D:") or path.startswith("\\"):
        return path
    # Relative path — prepend data root
    return DATA_PREFIX + path


def _cron_human(cron, task: dict = None) -> str:
    """将 cron 表达式转为可读文本"""
    if not cron:
        return "手动执行"
    if isinstance(cron, list):
        parts = [_cron_single(c, task) for c in cron]
        # Deduplicate
        seen = set()
        unique = []
        for p in parts:
            if p not in seen:
                seen.add(p)
                unique.append(p)
        return " / ".join(unique)
    return _cron_single(cron, task)


def _cron_single(cron: str, task: dict = None) -> str:
    parts = cron.strip().split()
    if len(parts) != 5:
        return cron
    minute, hour, dom, month, dow = parts
    time_str = f"{hour.zfill(2)}:{minute.zfill(2)}"
    prefix = ""
    if dow != "*":
        if dow in ("1-5", "1,2,3,4,5", "1,2,3,4,5,6,7"):
            prefix = "工作日 "
        elif dow in ("0,6", "6,0"):
            prefix = "周末 "
        else:
            prefix = f"周{dow} "
    elif dom != "*":
        prefix = f"每月{dom}日 "
    elif month != "*":
        prefix = f"{month}月 "
    if task and task.get("repeat"):
        r = task["repeat"]
        du_h = r["duration_min"] // 60
        du_m = r["duration_min"] % 60
        du_str = f"{du_h:02d}:{du_m:02d}" if du_h else f"00:{du_m:02d}"
        return f"{prefix}{time_str} (每{r['interval_min']}分钟至{du_str})"
    return f"{prefix}{time_str}"


# Will be set before generation
_META = {}


def _sort_key(task: dict) -> tuple:
    """按部门 + cron 时间排序"""
    dept_order = {"front-office": 0, "intelligence": 1, "engineering": 2, "rd": 3, "reader": 4}
    dept = task.get("dept", "zzz")
    cron = task.get("cron", "")
    if isinstance(cron, list):
        cron = cron[0] if cron else ""
    # Extract hour+minute for sorting
    parts = str(cron).split()
    hm = parts[1] + parts[0] if len(parts) >= 2 else "9999"
    return (dept_order.get(dept, 99), hm)


def _cron_to_schtasks(cron_str: str) -> dict:
    """Parse single cron into schtasks params"""
    parts = cron_str.strip().split()
    if len(parts) != 5:
        return {"sc": "DAILY", "st": "09:00", "days": None}
    minute, hour, dom, month, dow = parts
    st = f"{hour.zfill(2)}:{minute.zfill(2)}"

    if dow != "*" and dom == "*":
        day_map = {"0": "SUN", "1": "MON", "2": "TUE", "3": "WED", "4": "THU", "5": "FRI", "6": "SAT"}
        days = []
        for part in dow.split(","):
            part = part.strip()
            if "-" in part:
                s, e = part.split("-")
                for i in range(int(s), int(e) + 1):
                    days.append(day_map[str(i % 7)])
            elif part in day_map:
                days.append(day_map[part])
        return {"sc": "WEEKLY", "st": st, "days": ",".join(days)}
    return {"sc": "DAILY", "st": st, "days": None}


def _repeat_schtasks(task: dict) -> tuple:
    """Get repetition params for schtasks"""
    r = task.get("repeat")
    if r:
        du_h = r["duration_min"] // 60
        du_m = r["duration_min"] % 60
        du_str = f"{du_h:02d}:{du_m:02d}" if du_h else f"00:{du_m:02d}"
        return (str(r["interval_min"]), du_str)
    return None


# ── 生成 .bat 文件 ──────────────────────────────────────────────


def generate_all_bats(meta: dict, tasks: list[dict], dry_run: bool = False) -> dict[str, str]:
    """生成所有 .bat 文件内容，返回 {filename: content}"""
    global _META
    _META = meta

    outputs = {}
    registered_bats = set()

    for task in tasks:
        if not task.get("enabled", True):
            continue
        bat_style = task.get("bat_style", "simple")
        generator = BAT_GENERATORS.get(bat_style)
        if not generator:
            print(f"  [WARN] 未知 bat_style '{bat_style}' for task {task['id']}, 使用 simple")
            generator = _bat_simple

        content = generator(meta, task)
        bat_name = f"run_{task['id']}.bat"

        # Avoid duplicate identical bats
        if bat_name in registered_bats:
            # For vv_radar_afternoon etc. - use same bat file
            pass

        outputs[bat_name] = content
        registered_bats.add(bat_name)

    return outputs


# ── 生成 register_all_tasks.ps1 ─────────────────────────────────


def generate_register_ps1(meta: dict, tasks: list[dict]) -> str:
    """生成 register_all_tasks.ps1"""
    lines = [
        "<#",
        ".SYNOPSIS",
        "    注册所有 Windows 定时任务 — 由 tools/generate_task_bats.py 自动生成",
        ".DESCRIPTION",
        "    读 data/tasks.json 定义，为所有 enabled win_task 注册/更新计划任务。",
        "    安全: CREATE-only（/F 覆盖已存在），从不先删后建。",
        "#>",
        "",
        "$ErrorActionPreference = 'Continue'",
        '$projectDir = "{}"'.format(meta["work_dir"]),
        "",
        "function Register-SimpleTask {",
        "    param($Name, $ScriptPath, $Schedule, $StartTime, $DaysOfWeek, $RepeatInterval, $Duration)",
        "    $extra = @()",
        "    if ($DaysOfWeek) { $extra += '/D', $DaysOfWeek }",
        "    if ($RepeatInterval) { $extra += '/RI', $RepeatInterval; $extra += '/DU', $Duration }",
        "    $args = @('/Create', '/TN', $Name, '/TR', \"cmd /c `\"$ScriptPath`\"\",",
        "             '/SC', $Schedule, '/ST', $StartTime) + $extra + @('/F', '/RL', 'HIGHEST')",
        "    $result = & schtasks $args 2>&1",
        '    if ($LASTEXITCODE -eq 0) { Write-Host "[OK] $Name ($StartTime)" -ForegroundColor Green }',
        '    else { Write-Host "[FAIL] $Name : $result" -ForegroundColor Red }',
        "}",
        "",
        "function Register-MultiTriggerTask {",
        "    param($Name, $ScriptPath, $Triggers)",
        "    $triggerList = @()",
        "    foreach ($t in $Triggers) {",
        "        if ($t.Days -and $t.Days -ne '') {",
        "            $triggerList += New-ScheduledTaskTrigger -Weekly -At $t.StartTime -DaysOfWeek $t.Days",
        "        } else {",
        "            $triggerList += New-ScheduledTaskTrigger -Daily -At $t.StartTime",
        "        }",
        "    }",
        "    $action = New-ScheduledTaskAction -Execute 'cmd.exe' -Argument \"/c `\"$ScriptPath`\"\"",
        "    Register-ScheduledTask -TaskName $Name -Trigger $triggerList -Action $action -RunLevel Limited -Force | Out-Null",
        '    Write-Host "[OK] $Name (multi-trigger)" -ForegroundColor Green',
        "}",
        "",
    ]

    # Collect registration entries
    enabled_tasks = [t for t in tasks if t.get("enabled", True) and t.get("type") == "win_task"]
    enabled_tasks.sort(key=_sort_key)

    # Register each task
    for task in enabled_tasks:
        name = task.get("name")
        if not name:
            continue

        bat_name = f"run_{task['id']}.bat"
        script_path = f"{meta['work_dir']}\\{bat_name}"
        cron = task.get("cron")

        # Parse cron(s)
        cron_list = [cron] if isinstance(cron, str) else (cron or [])

        if len(cron_list) == 1:
            # Single trigger
            sched = _cron_to_schtasks(cron_list[0])
            repeat = _repeat_schtasks(task)
            rep_param = ""
            if repeat:
                rep_param = f" -RepeatInterval '{repeat[0]}' -Duration '{repeat[1]}'"
            days_param = f" -DaysOfWeek '{sched['days']}'" if sched["days"] else ""

            lines.append(f"# {task['description']}")
            lines.append(
                f"Register-SimpleTask -Name '{name}' -ScriptPath '{script_path}'"
                f" -Schedule '{sched['sc']}' -StartTime '{sched['st']}'"
                f"{days_param}{rep_param}"
            )
            lines.append("")
        elif len(cron_list) > 1:
            # Multi-trigger
            lines.append(f"# {task['description']}")
            lines.append(f"$triggers = @(")
            for i, c in enumerate(cron_list):
                sched = _cron_to_schtasks(c)
                if sched["days"]:
                    days_ps = "'" + "','".join(sched["days"].split(",")) + "'"
                    lines.append(f"    @{{StartTime='{sched['st']}'; Days=@({days_ps})}}" + ("," if i < len(cron_list)-1 else ""))
                else:
                    lines.append(f"    @{{StartTime='{sched['st']}'; Days=''}}" + ("," if i < len(cron_list)-1 else ""))
            lines.append(")")
            lines.append(
                f"Register-MultiTriggerTask -Name '{name}' -ScriptPath '{script_path}' -Triggers $triggers"
            )
            lines.append("")

    # Validation block
    lines.extend([
        "",
        "# ── 验证 ──",
        'Write-Host "`n=== 验证 ===" -ForegroundColor Cyan',
        "$allOk = $true",
        "$checkNames = @(",
    ])
    for i, task in enumerate(enabled_tasks):
        name = task.get("name")
        if name:
            sep = "," if i < len(enabled_tasks) - 1 else ""
            lines.append(f"    '{name}'{sep}")
    lines.extend([
        ")",
        "foreach ($n in $checkNames) {",
        "    $q = schtasks /Query /TN $n /FO LIST 2>&1",
        "    if ($LASTEXITCODE -eq 0) {",
        '        Write-Host "[OK] $n" -ForegroundColor Green',
        "    } else {",
        '        Write-Host "[MISSING] $n - CRITICAL" -ForegroundColor Red',
        "        $allOk = $false",
        "    }",
        "}",
        'if ($allOk) { Write-Host "`nAll tasks verified OK" -ForegroundColor Green }',
        'else { Write-Host "`nSOME TASKS FAILED VERIFICATION" -ForegroundColor Red; exit 1 }',
        "",
    ])

    return "\n".join(lines)


# ── 主流程 ──────────────────────────────────────────────────────


def main():
    dry_run = "--dry-run" in sys.argv or "-n" in sys.argv
    do_backup = "--backup" in sys.argv or "-b" in sys.argv

    # Load tasks.json
    if not TASKS_JSON.exists():
        print(f"[ERROR] {TASKS_JSON} not found")
        sys.exit(1)

    data = json.loads(TASKS_JSON.read_text(encoding="utf-8"))
    meta = data["meta"]
    tasks = data["tasks"]

    print(f"[generate_task_bats] 源文件: {TASKS_JSON}")
    print(f"[generate_task_bats] {len(tasks)} 任务, Python: {meta['python_path']}")
    print(f"[generate_task_bats] 工作目录: {meta['work_dir']}")
    if dry_run:
        print("[generate_task_bats] DRY RUN 模式 — 不会写盘")
    print()

    # Backup
    if do_backup and not dry_run:
        _do_backup(meta)

    # Generate .bat files
    bat_outputs = generate_all_bats(meta, tasks, dry_run=dry_run)
    enabled_win = sum(1 for t in tasks if t.get("enabled", True) and t.get("type") == "win_task")
    enabled_manual = sum(1 for t in tasks if t.get("enabled", True) and t.get("type") == "manual_bat")
    print(f"[generate_task_bats] 生成 {len(bat_outputs)} 个 .bat 文件 ({enabled_win} 定时 + {enabled_manual} 手动)")

    # Generate register_all_tasks.ps1
    ps1_content = generate_register_ps1(meta, tasks)
    print(f"[generate_task_bats] 生成 register_all_tasks.ps1 ({enabled_win} 任务注册)")

    # Generate tasks_summary.md
    summary_content = generate_summary(meta, tasks)
    print(f"[generate_task_bats] 生成 tasks_summary.md")

    if dry_run:
        print("\n[DRY RUN] 以下文件将被写入:")
        for bat_name in sorted(bat_outputs):
            print(f"  {bat_name}")
        print(f"  register_all_tasks.ps1")
        print(f"  tasks_summary.md")
        return

    # Write files
    (BASE_DIR / "tasks_summary.md").write_text(summary_content, encoding="utf-8")
    print(f"  ✓ tasks_summary.md")

    ps1_path = BASE_DIR / "register_all_tasks.ps1"
    ps1_path.write_text(ps1_content, encoding="utf-8")
    print(f"  ✓ register_all_tasks.ps1")

    written = 0
    for bat_name, content in sorted(bat_outputs.items()):
        bat_path = BASE_DIR / bat_name
        bat_path.write_text(content, encoding="utf-8")
        written += 1
    print(f"  ✓ {written} 个 .bat 文件")

    # Summary
    print(f"\n[generate_task_bats] 完成! 共生成 {written} .bat + register_all_tasks.ps1 + tasks_summary.md")


def generate_summary(meta: dict, tasks: list[dict]) -> str:
    """生成 tasks_summary.md"""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    dept_names = {"front-office": "前厅部", "intelligence": "情报部", "engineering": "工程部", "rd": "研发部", "reader": "读书郎"}

    lines = [
        f"# 定时任务一览 | {now}",
        "",
        f"Python: `{meta['python_path']}`",
        f"工作目录: `{meta['work_dir']}`",
        f"数据来源: `data/tasks.json`",
        "",
        "---",
        "",
        "## 汇总",
        "",
    ]

    total = len(tasks)
    enabled = sum(1 for t in tasks if t.get("enabled"))
    win_task = sum(1 for t in tasks if t.get("type") == "win_task")
    manual = sum(1 for t in tasks if t.get("type") == "manual_bat")
    disabled = sum(1 for t in tasks if not t.get("enabled"))

    lines.append(f"- 任务总数: {total} (启用 {enabled}, 禁用 {disabled})")
    lines.append(f"- Windows 定时任务: {win_task}")
    lines.append(f"- 手动脚本: {manual}")
    lines.append("")

    for dept_key, dept_label in dept_names.items():
        dept_tasks = [t for t in tasks if t.get("dept") == dept_key]
        if not dept_tasks:
            continue
        lines.append(f"### {dept_label}")
        lines.append("")
        lines.append("| 任务 | 说明 | 时间 | 脚本 |")
        lines.append("|------|------|------|------|")
        for t in sorted(dept_tasks, key=_sort_key):
            name = t.get("name") or t["id"]
            desc = t["description"]
            cron = _cron_human(t.get("cron"), t)
            if "steps" in t:
                first_cmd = t["steps"][0]["command"] if t["steps"] else "N/A"
                script = f"`{first_cmd}` (+{len(t['steps'])-1}步)"
            else:
                script = f"`{t['command']}`"
            status = " ⛔" if not t.get("enabled") else ""
            lines.append(f"| {name}{status} | {desc} | {cron} | {script} |")
        lines.append("")

    lines.append("---")
    lines.append(f"*自动生成于 {now} | 修改 tasks.json 后重新运行 `python tools/generate_task_bats.py`*")
    lines.append("")

    return "\n".join(lines)


def _do_backup(meta: dict):
    """备份现有 .bat 和注册脚本"""
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    count = 0
    for f in sorted(BASE_DIR.glob("run_*.bat")):
        shutil.copy2(f, BACKUP_DIR / f.name)
        count += 1
    for f in sorted(BASE_DIR.glob("register_*.ps1")):
        shutil.copy2(f, BACKUP_DIR / f.name)
        count += 1
    print(f"[backup] 已备份 {count} 个文件到 {BACKUP_DIR}")


if __name__ == "__main__":
    main()
